---
title: "Code for reproducible results for the paper “Assessing the validity of register-based and microsimulated kinship networks for demographic research”"
output:
  github_document:
    pandoc_args: --webtex
    toc: true
    toc_depth: 1
bibliography: registers.bib
---

```{r setup, include=FALSE}
# General set up, change if message and warnings should be included
knitr::opts_chunk$set(echo = FALSE, 
                      message = FALSE, 
                      warning = FALSE, 
                      fig.align='center')
```
# Introduction

Estimating kinship networks is data-demanding and mainly possible using empirical sources or demographic models. Empirical micro-level data, like population registers, provide a realistic picture but are scarce and limited by truncation and survivorship bias. Demographic models like microsimulation use aggregated data, but only minimally account for population heterogeneity, family similarity and non-marital fertility. We analyse the differences between approaches by examining the correspondence in size and structure of kinship networks derived from empirical and microsimulated data. We compare the number of kin from grandparents to grandchildren for the Swedish population (cohorts 1915-2017), estimated based on contemporary Swedish population registers [@kolk_swedish_2023] and the SOCSIM microsimulation programme. We use the SOCSIM demographic microsimulation program and data for Sweden from the [Human Fertility Collection (HFC)](https://www.fertilitydata.org/) (1751-1890), the [Human Fertility Database (HFD)](https://www.humanfertility.org/) (1891-2017), and the [Human Mortality Database (HMD)](https://www.mortality.org/) (1751-2017). Our results show that mean numbers and distributions of most kin are similar across both sources. The microsimulation produces slightly lower numbers of kin for cohorts unaffected by truncation in the registers, but better accounts for kin of early cohorts that are under-registered due to missing parent-child links, conditioning on survival or migration. Although a systematic comparison of empirical and microsimulated kinship networks is only possible for a few countries like Sweden, our assessment of the accuracy of synthetic kinship networks may serve as a reference for research using microsimulation to study kinship in other contexts.

# Scripts for reproducible results

**NB**: If you want to re-run the analysis from scratch (i.e., retrieve the data from [HFC](https://www.fertilitydata.org/), [HFD](https://www.humanfertility.org/), and [HMD](https://www.mortality.org/)), run the microsimulations and reproduce the results), you need R, some standard packages, `HMDHFDplus` and `rsocsim`. 
Please, follow these steps:

1. Download this repository to your computer.  
2. Register at [HFD](https://www.humanfertility.org/) and [HMD](https://www.mortality.org/) and install `HMDHFDplus`.  
To write the input rate files and to compare the simulation results with the original input data, we use data from [HFC](https://www.fertilitydata.org/), [HFD](https://www.humanfertility.org/), and [HMD](https://www.mortality.org/). The last two are retrieved through the `HMDHFDplus` package. To gain full access to the databases, you need to become a registered user at both databases, after accepting the user agreement on their websites: <https://www.humanfertility.org/Account/Auth> and <https://mortality.org/Account/Auth>. 
3. Install `rsocsim`.  
Please go to <https://github.com/MPIDR/rsocsim> to find the instructions on how to install `rsocsim`.  
4. Open the provided RStudio project. 
5. Run the scripts sequentially in the order suggested by the numbers of the files (0-3). 
6. In scripts 0 and 1, please type your username and password for [HFD](https://www.humanfertility.org/) and [HMD](https://www.mortality.org/) in the corresponding space before running the code.  
7. To get exactly the same simulation results, you should use the same randomly generated seed mentioned in script 0.

# References